version: '3.1'

services:
  nginx:
    image: nginx:latest
    links:
      - core
      - frontend
    depends_on:
      - core
      - frontend
    ports:
      - 3000:80
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
  
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
  
  core:
    build: ./core
    depends_on:
      - example-plugin
    volumes:
      - ./:/app
  
  example-plugin:
    build: ./packages/example-plugin
    volumes:
      - ./:/app
