version: '3.1'

services:
  nginx:
    image: nginx:latest
    ports:
      - 3000:80
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
  
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
  
  go:
    build: .
    volumes:
      - ./:/app
