root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["infinity"]
  bin = "/bin/sleep"
  cmd = "go build -buildmode=plugin -o ../../build/example-plugin.so ."
  delay = 1000
  exclude_dir = ["frontend", "build", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false